author:
  name:
  twitter:
  picture:
twitter_username:
github_username:
discord: gwamp7n
logo: # path of site logo, e.g. "/assets/images/logo.png"
search: # true, false (default)
search_full_content: false # true, false (default)
search_provider: # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false
